version: '3.0'

services:
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SpringBootDemo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
