version: '3.0'

services:
  java_app:
    container_name: java_app
    image: java_app:1.0
    build: ./
    ports:
      - 8085:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5433/SpringBootDemo
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db
    networks:
      - java_app
  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SpringBootDemo
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - java_app

volumes:
  pgdata: {}

networks:
  java_app:
